export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const GET_USER_INFO_START = 'GET_USER_INFO_START'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED'
export const CLEAN_USER_INFO = 'CLEAN_USER_INFO'

// export const ADMIN_CREATE_ARTICLE_START = 'ADMIN_CREATE_ARTICLE_START'

export const GET_TOP_NEWS_START = 'GET_TOP_NEWS_START'
export const GET_TOP_NEWS_SUCCESS = 'GET_TOP_NEWS_SUCCESS'
export const GET_TOP_NEWS_FAILED = 'GET_TOP_NEWS_FAILED'

export const GET_RECENT_NEWS_START = 'GET_RECENT_NEWS_START'
export const GET_RECENT_NEWS_SUCCESS = 'GET_RECENT_NEWS_SUCCESS'
export const GET_RECENT_NEWS_FAILED = 'GET_RECENT_NEWS_FAILED'

export const GET_ARTICLE_START = 'GET_ARTICLE_START'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED'
export const TOGGLE_COMMENT_SECTION = 'TOGGLE_COMMENT_SECTION'
export const ARTICLE_UPDATE = 'ARTICLE_UPDATE'
export const CLEAN_ARTICLE = 'CLEAN_ARTICLE'

export const REMOVE_ERROR = 'REMOVE_ERROR'